### ISSUE TITLE
Form表单中的IBestCascader有误

### ISSUE THREAD

**Issue by fyt135** [ibestservices/ibest-ui#17]
Form表单的自定义表单项类型案例代码有误，缺少了@link修饰的value，但是加上去之后页面无法打开了，直接闪退。
Device info:emulator
Build info:emulator 5.0.0.65(SP73DEVC00E65R4P11log)
Fingerprint:859b25bfba4e922df88606c8510f0dccfc7547c7a4cf055c9851d69bf88d22cd
Module name:com.example.myapplication
Version:1.0.0
VersionCode:1000000
PreInstalled:No
Foreground:Yes
Pid:24249
Uid:20020042
Reason:TypeError
Error name:TypeError
Error message:is not callable
Stacktrace:
    at SynchedPropertyTwoWayPU (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:5799:1)
    at SynchedPropertyObjectTwoWayPU (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:0:1)
    at IBestCascader (oh_modules/.ohpm/@ibestservices+ibest-ui@1.13.0/oh_modules/@ibestservices/ibest-ui/src/main/ets/components/cascader/index.ets:327:117)
    at anonymous (entry/src/main/ets/pages/DemoPage.ets:197:28)
    at updateFunc (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6778:1)
    at observeComponentCreation2 (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6819:1)
    at initialRender (entry/src/main/ets/pages/DemoPage.ets:197:28)
    at initialRenderView (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6475:1)
    at anonymous (entry/src/main/ets/pages/Index.ets:55:9)

**Comment by damengbuxing** [comment]
你好,文档上是漏写了, 请提供一下绑定详细代码

**Comment by fyt135** [comment]
我之前写错了，没事了

**Comment by damengbuxing** [comment]
可以加下qq群,方便交流 953492584
